#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# 04_compare_miniGhost.sh — CPU vs GPU performance comparison
# Auto-generated by 03_apply_gpu_patch.py
#
# Uses np=1 (single process) for reliable GPU comparison.
# CPU uses system MPI, GPU uses NVIDIA HPC SDK MPI.
###############################################################################

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="miniGhost"
RUNS="${RUNS:-3}"
CPU_BIN="$PROJECT_ROOT/apps/${APP}_build/${APP}_normal"
GPU_SRC="$PROJECT_ROOT/apps/${APP}_gpu/ref"
REPORT="$PROJECT_ROOT/reports/$APP/performance_comparison"
mkdir -p "$REPORT"

log() { echo -e "\n\033[1;32m[$(date +%H:%M:%S)] $*\033[0m"; }

# ======================== Find binaries ========================
# CPU binary
if [ ! -x "$CPU_BIN" ] && [ -x "${CPU_BIN}.x" ]; then
    CPU_BIN="${CPU_BIN}.x"
fi
[ -x "$CPU_BIN" ] || { echo "CPU binary not found. Run 01_profile_app.sh first."; exit 1; }

# GPU binary — build if needed
GPU_BIN=""
if [ -f "$GPU_SRC/makefile.gpu" ]; then
    log "Building GPU version..."
    cd "$GPU_SRC"
    make -f makefile.gpu clean 2>/dev/null || true
    make -f makefile.gpu 2>&1 | tee "$REPORT/build_gpu.log"
fi
for candidate in "$GPU_SRC/miniGhost_gpu.x" "$GPU_SRC/miniGhost.x" "$GPU_SRC/XSBench"; do
    if [ -x "$candidate" ]; then GPU_BIN="$candidate"; break; fi
done
if [ -z "$GPU_BIN" ]; then
    GPU_BIN=$(find "$GPU_SRC" -maxdepth 1 -type f -executable | head -1)
fi
[ -n "$GPU_BIN" ] && [ -x "$GPU_BIN" ] || { echo "GPU build failed - no binary found"; exit 1; }

export ACC_DEVICE_TYPE=nvidia

# ======================== Run comparison ========================
TS=$(date +%Y%m%d_%H%M%S)
RESULT_FILE="$REPORT/comparison_$TS.txt"
RUN_ARGS="--nx 100 --ny 100 --nz 100 --num_tsteps 20 --num_vars 5"

{
echo "========================================================"
echo "  $APP CPU vs GPU Performance Comparison"
echo "  Date: $(date)"
echo "  CPU: $CPU_BIN"
echo "  GPU: $GPU_BIN"
echo "  GPU device: $(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null || echo N/A)"
echo "  Runs: $RUNS"
echo "  Args: $RUN_ARGS"
echo "========================================================"
echo ""

# --- CPU baseline ---
log "CPU Baseline ($RUNS runs)"
cpu=()
for i in $(seq 1 $RUNS); do
    t0=$(date +%s%N)
    mpirun --oversubscribe --allow-run-as-root -np 1 "$CPU_BIN" $RUN_ARGS >/dev/null 2>&1
    ms=$(( ($(date +%s%N) - t0) / 1000000 )); cpu+=($ms)
    echo "  Run $i: ${ms}ms"
done
cs=0; for t in "${cpu[@]}"; do cs=$((cs+t)); done; ca=$((cs/RUNS))
echo "  Average: ${ca}ms"

# --- GPU version ---
log "GPU Version ($RUNS runs)"
gpu=()
for i in $(seq 1 $RUNS); do
    t0=$(date +%s%N)
    /opt/nvidia/hpc_sdk/Linux_x86_64/26.1/comm_libs/mpi/bin/mpirun --oversubscribe -np 1 "$GPU_BIN" $RUN_ARGS >/dev/null 2>&1
    ms=$(( ($(date +%s%N) - t0) / 1000000 )); gpu+=($ms)
    echo "  Run $i: ${ms}ms"
done
gs=0; for t in "${gpu[@]}"; do gs=$((gs+t)); done; ga=$((gs/RUNS))
echo "  Average: ${ga}ms"

# --- Summary ---
sp=$(awk "BEGIN{printf \"%.2f\",$ca/($ga>0?$ga:1)}")
echo ""
echo "========================================================"
echo "  CPU avg: ${ca}ms  |  GPU avg: ${ga}ms  |  Speedup: ${sp}x"
echo "========================================================"

} 2>&1 | tee "$RESULT_FILE"

log "Results saved to: $RESULT_FILE"
